// server/src/models/PostMedia.model.js

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const PostMedia = sequelize.define(
  'PostMedia',
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },

    postId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'posts',
        key: 'id',
      },
      onDelete: 'CASCADE',
    },

    // ─── Media URL (image or video) ────────────────────
    url: {
      type: DataTypes.TEXT,
      allowNull: false,
      field: 'media_url', // Map to existing database column
      validate: {
        notEmpty: true,
      },
    },

    // ─── Thumbnail URL (for videos only) ──────────────
    // For images: null (use url directly)
    // For videos: auto-generated by Cloudinary
    thumbnailUrl: {
      type: DataTypes.TEXT,
      allowNull: true,
      field: 'small_url', // Map to existing database column
    },

    // ─── Media type ───────────────────────────────────
    // 'image' | 'video'
    mediaType: {
      type: DataTypes.ENUM('image', 'video'),
      allowNull: false,
      defaultValue: 'image',
    },

    // ─── Cloudinary public ID (for deletion) ──────────
    publicId: {
      type: DataTypes.STRING(255),
      allowNull: true,
    },

    // ─── Video duration in seconds ────────────────────
    // null for images
    // e.g. 45 for a 45-second video
    duration: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },

    // ─── Display order in carousel ────────────────────
    // 0 = first image/video
    order: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
      field: 'display_order', // Map to existing database column
    },

    // ─── Image dimensions (optional metadata) ─────────
    width: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },

    height: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
  },
  {
    tableName: 'post_media',
    underscored: true,
    timestamps: true,
    indexes: [
      {
        fields: ['post_id'],
      },
      {
        fields: ['media_type'],
      },
    ],
  }
);

module.exports = PostMedia;