// server/src/models/Reel.model.js

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Reel = sequelize.define(
    'Reel',
    {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
        },

        // ─── Owner ────────────────────────────────────────
        userId: {
            type: DataTypes.UUID,
            allowNull: false,
            references: {
                model: 'users',
                key: 'id',
            },
            onDelete: 'CASCADE',
        },

        // ─── Video ────────────────────────────────────────
        videoUrl: {
            type: DataTypes.TEXT,
            allowNull: false,
            validate: {
                notEmpty: true,
            },
        },

        // ─── Thumbnail (auto-generated by Cloudinary) ─────
        thumbnailUrl: {
            type: DataTypes.TEXT,
            allowNull: true,
        },

        // ─── Cloudinary public_id (for deletion) ──────────
        publicId: {
            type: DataTypes.STRING(255),
            allowNull: true,
        },

        // ─── Video metadata ───────────────────────────────
        // Duration in seconds (max 60)
        duration: {
            type: DataTypes.INTEGER,
            allowNull: true,
            validate: {
                min: 1,
                max: 60,
            },
        },

        // Video dimensions
        width: {
            type: DataTypes.INTEGER,
            allowNull: true,
        },

        height: {
            type: DataTypes.INTEGER,
            allowNull: true,
        },

        // ─── Content ──────────────────────────────────────
        caption: {
            type: DataTypes.TEXT,
            allowNull: true,
            validate: {
                len: [0, 2200],
            },
        },

        // ─── Audio / Music metadata ───────────────────────
        // Name of audio track if user added music (future)
        audioName: {
            type: DataTypes.STRING(500),
            allowNull: true,
        },

        // Original audio from video or custom track
        audioType: {
            type: DataTypes.ENUM('original', 'music'),
            allowNull: false,
            defaultValue: 'original',
        },

        // ─── Engagement counts (denormalized for speed) ───
        likesCount: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
        },

        commentsCount: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
        },

        // Number of times video was played
        playsCount: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
        },

        // Number of shares
        sharesCount: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
        },

        // ─── Visibility ───────────────────────────────────
        isPublic: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        },
        mentions: {
            type: DataTypes.JSONB,
            allowNull: false,
            defaultValue: [],
        },
        categories: {
            type: DataTypes.JSONB,
            allowNull: false,
            defaultValue: [],
        },
    },
    {
        tableName: 'reels',
        underscored: true,
        timestamps: true,
        indexes: [
            { fields: ['user_id'] },
            { fields: ['created_at'] },
            { fields: ['likes_count'] },
            { fields: ['plays_count'] },
        ],
    }
);

module.exports = Reel;