// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:instagram_client/features/chat/data/models/chat_user.dart';
import 'package:instagram_client/features/chat/data/models/conversation.dart';
import 'package:instagram_client/features/chat/data/models/message.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatUserAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(MessageAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatUserAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(MessageAdapter());
  }
}
